spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${services.auth}
              predicates:
                - Path=/api/v1/auth/**
            - id: user-service
              uri: ${services.users}
              predicates:
                - Path=/api/v1/users/**
            - id: product-service
              uri: ${services.products}
              predicates:
                - Path=/api/v1/products/**, /api/v1/categories/**


server:
  port: 8080

services:
  auth: http://localhost:8081
  users: http://localhost:8082
  products: http://localhost:8083
