spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${services.auth}
              predicates:
                - Path=/api/v1/auth/**
            - id: user-service
              uri: ${services.users}
              predicates:
                - Path=/api/v1/users/**
            - id: product-service
              uri: ${services.products}
              predicates:
                - Path=/api/v1/products/**, /api/v1/categories/**
            - id: inventory-service
              uri: ${services.inventory}
              predicates:
                - Path=/api/v1/inventory/**
              filters:
                - AddRequestHeader=X-Internal-Call, true
            - id: order-service
              uri: ${services.orders}
              predicates:
                - Path=/api/v1/orders/**


server:
  port: 8080

services:
  auth: http://localhost:8081
  users: http://localhost:8082
  products: http://localhost:8083
  inventory: http://localhost:8084
  orders: http://localhost:8085

security:
  jwt:
    secret: sua-chave-secreta-muito-segura-para-producao-minimo-256-bits

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger
    urls:
      - name: auth-service
        url: ${services.auth}/v3/api-docs
      - name: user-service
        url: ${services.users}/v3/api-docs
      - name: product-service
        url: ${services.products}/v3/api-docs
      - name: inventory-service
        url: ${services.inventory}/v3/api-docs
      - name: order-service
        url: ${services.orders}/v3/api-docs
